// Manages a user's grocery list. The list is generated by pulling all ingredients from the user's saved recipes
// and classifying each one into a store section (Produce, Protein, Dairy, Pantry, Other).
const GroceryItem = require('../models/GroceryItem');
const Favorite    = require('../models/Favorite');

// Keyword lists used to classify an ingredient into its store aisle section.
const SECTION_MAP = {
  produce: [
    'tomato', 'tomatoes', 'onion', 'onions', 'garlic', 'ginger',
    'pepper', 'peppers', 'spinach', 'lettuce', 'avocado', 'lemon',
    'lime', 'potato', 'potatoes', 'plantain', 'plantains', 'carrot',
    'carrots', 'celery', 'cucumber', 'mushroom', 'mushrooms',
    'sweet potato', 'cherry tomatoes', 'basil', 'coriander', 'thyme',
    'rosemary', 'mint', 'parsley', 'chilli', 'chillies', 'scotch bonnet',
    'red pepper', 'green pepper', 'bell pepper',
  ],
  protein: [
    'chicken', 'beef', 'salmon', 'prawn', 'prawns', 'fish', 'lamb',
    'pork', 'egg', 'eggs', 'meat', 'mince', 'minced beef', 'chicken breast',
    'chicken thigh', 'stockfish', 'assorted meat', 'tofu', 'chickpeas',
    'edamame', 'beans', 'lentils',
  ],
  dairy: [
    'milk', 'butter', 'cream', 'cheese', 'parmesan', 'mozzarella',
    'feta', 'yoghurt', 'double cream', 'unsalted butter',
  ],
  pantry: [
    'flour', 'sugar', 'salt', 'oil', 'olive oil', 'vegetable oil',
    'rice', 'pasta', 'noodles', 'stock', 'coconut milk', 'tomato paste',
    'soy sauce', 'fish sauce', 'honey', 'vinegar', 'yeast', 'baking powder',
    'cumin', 'paprika', 'turmeric', 'curry powder', 'nutmeg', 'cinnamon',
    'bay leaves', 'cloves', 'tahini', 'quinoa', 'breadcrumbs', 'wine',
    'red wine', 'white wine', 'tamarind', 'palm oil', 'crayfish',
    'seasoning', 'seasoning cubes', 'icing sugar', 'caster sugar',
    'plain flour', 'cocoa powder', 'dark chocolate', 'maple syrup',
    'sesame seeds', 'peanuts', 'groundnuts',
  ],
};

function getSection(ingredientName) {
  const lower = ingredientName.toLowerCase();
  for (const [section, keywords] of Object.entries(SECTION_MAP)) {
    if (keywords.some(k => lower.includes(k))) {
      return section.charAt(0).toUpperCase() + section.slice(1);
    }
  }
  return 'Other';
}

const generateList = async (req, res, next) => {
  try {
    const favorites = await Favorite.find({ user: req.user._id })
      .populate('recipe');

    if (!favorites.length) {
      return res.status(400).json({
        message: 'You have no saved recipes. Save some recipes first.',
      });
    }

    await GroceryItem.deleteMany({ user: req.user._id });

    const items = [];
    for (const fav of favorites) {
      const recipe = fav.recipe;
      if (!recipe) continue;
      for (const ing of recipe.ingredients) {
        items.push({
          user:     req.user._id,
          name:     ing.name,
          quantity: ing.quantity,
          recipe:   recipe.title,
          section:  getSection(ing.name),
          checked:  false,
        });
      }
    }

    const inserted = await GroceryItem.insertMany(items);
    res.status(201).json(inserted);
  } catch (err) { next(err); }
};

const getList = async (req, res, next) => {
  try {
    const items = await GroceryItem.find({ user: req.user._id })
      .sort({ section: 1, name: 1 });
    res.json(items);
  } catch (err) { next(err); }
};

const toggleItem = async (req, res, next) => {
  try {
    const item = await GroceryItem.findOne({
      _id:  req.params.id,
      user: req.user._id,
    });
    if (!item) return res.status(404).json({ message: 'Item not found' });
    item.checked = !item.checked;
    await item.save();
    res.json(item);
  } catch (err) { next(err); }
};

const clearCompleted = async (req, res, next) => {
  try {
    await GroceryItem.deleteMany({ user: req.user._id, checked: true });
    const remaining = await GroceryItem.find({ user: req.user._id })
      .sort({ section: 1, name: 1 });
    res.json(remaining);
  } catch (err) { next(err); }
};

const resetList = async (req, res, next) => {
  try {
    await GroceryItem.updateMany(
      { user: req.user._id },
      { checked: false }
    );
    const items = await GroceryItem.find({ user: req.user._id })
      .sort({ section: 1, name: 1 });
    res.json(items);
  } catch (err) { next(err); }
};

module.exports = { generateList, getList, toggleItem, clearCompleted, resetList };
